apm install atom-beautify
 apm install atom-material-ui
 apm install atom-prettify
 apm install atom-ternjs
 apm install autoclose-html
 apm install autocomplete-paths
 apm install busy-signal
 apm install chester-atom-syntax
 apm install emmet
 apm install expand-region
 apm install language-graphql
 apm install language-pug-jade
 apm install linter
 apm install linter-eslint
 apm install linter-pug
 apm install linter-ui-default
 apm install open-in-browser
 apm install pigments
 apm install prettier-atom
 apm install react
 apm install seti-icons
 apm install standard-formatter
